### ISSUE TITLE
train_covid19

### ISSUE THREAD

**Issue by Gnazio** [jannisborn/covid19_ultrasound#100]
Hi, thanks for sharing this project and correlated code with the community. First time to use GitHub so feel free to redirect to the rigth repository.  I have a problem with the train_covid19.py file, "python3 scripts/train_covid19.py --data_dir ../data/cross_validation/ --fold 0 --epochs 2 ", the read.me file suggest to run this code from the directory but it doesnt work for me and states that the syntax is wrong, my IDE is PyCharm.
So i tried to run the train_covid19.py file, but it states: "the following arguments are required: -d/--data_dir"? The other files database_genrator and cross-vall split seem to work if runned directly, but not the train one. Can you suggest me a fix?

Thanks for the help.
Giacomo

**Comment by jannisborn** [comment]
hey @Gnazio,
thanks for your interest in our work. You need to run this command from within the `pocovidnet` folder because otherwise the relative path `scripts/train_covid19.py` will not be reachable. As you can see from the command, the `cross_validation` folder needs to be available under `data`, so you need to create the data split first. Please make sure to create a meaningful split, otherwise your results are garbaga (see README for details).
Also, if it says that `-d` is required, maybe there's a line break in the command when copypaste it into your IDE.

**Comment by jannisborn** [comment]
Feel free to reopen if applicable
