### ISSUE TITLE
test train

### ISSUE THREAD

**Issue by Gnazio** [jannisborn/covid19_ultrasound#101]
Hi hello again, thanks for the last time,  i didnt immediatly close the issue cause i tested this morning and now it work, but it does not work the following cmd:
python scripts/test.py [-h] [--data DATA] [--weights WEIGHTS] [--m_id M_ID] [--classes CLASSES] [--folds FOLDS] [--save_path SAVE_PATH]
it tells me "test.py: error: unrecognized arguments: [-h] [--data DATA] [--weights WEIGHTS] [--m_id M_ID] [--classes CLASSES] [--folds FOLDS] [--save_path SAVE_PATH]" 
i dont get it? I have to put the correct directory, weigth etc.? from files inside the pocovidnet packages?

Thanks for the help.

**Comment by NinaWie** [comment]
Hi @Gnazio , running our code requires some experience in Python, so you should probably check out some tutorials first. [Here](https://www.tutorialspoint.com/python/python_command_line_arguments.htm) you can for example find a description how command line arguments in Python work. 

In the line that you sent, the brackets [] are a placeholder and it means that you have to input the correct values yourself. In other words, you have to put it in the following form (and change it to the correct paths). 
```
python3 scripts/test.py --data_dir "path/to/input/data" --weights "path/to/weights" 
```
The weights of a pretrained model can be downloaded as explained [here](https://github.com/jannisborn/covid19_ultrasound/tree/master/pocovidnet#pretrained-models).

I'm closing this issue again because this is not a problem of our code or documentation.
