### ISSUE TITLE
Butterfly dataset no long available

### ISSUE THREAD

**Issue by CaelynCheung1996** [jannisborn/covid19_ultrasound#117]
I clicked on the link to the Butterfly gallery and found 404 error. Seems they are no longer available.

**Comment by jannisborn** [comment]
This might totally be the case. There's nothing I can do in this case. 

Maybe only the URLs changed? Can you find covid videos somewhere else on the website? If yes, feel free to open a PR. 
Also consider to contact butterfly directly and ask for the data.

**Comment by jannisborn** [comment]
This might totally be the case. There's nothing I can do in this case. 

Maybe only the URLs changed? Can you find covid videos somewhere else on the website? If yes, feel free to open a PR. 
Also consider to contact butterfly directly and ask for the data.

**Comment by CaelynCheung1996** [comment]
> This might totally be the case. There's nothing I can do in this case.
> 
> Maybe only the URLs changed? Can you find covid videos somewhere else on the website? If yes, feel free to open a PR. Also consider to contact butterfly directly and ask for the data.

Thanks I will double check but I think they might be gone. In addition, I could not find information about the Bolzano AG data. Could you provide more information how to download them? Thanks.

**Comment by CaelynCheung1996** [comment]
> This might totally be the case. There's nothing I can do in this case.
> 
> Maybe only the URLs changed? Can you find covid videos somewhere else on the website? If yes, feel free to open a PR. Also consider to contact butterfly directly and ask for the data.

You may want to refer this repository for the updated Butterfly gallery link: https://github.com/nrc-cnrc/COVID-US/blob/main/utils/video_metadata.csv

**Comment by jannisborn** [comment]
@CaelynCheung1996:

- The Bolzano data was recorded in Italy in the first wave of the pandemic. We had it available online via this repo for a while but then removed it because the data quality was too low. There was uncertainty about the classification of the videos, no PCR tests were available at that time, so there was no actual ground truth on diagnostic labels
- Thanks for sharing this link. Keep in mind that this repo is a seamless copy of our repo/dataset but in this case, they had saved the direct download URL in the `csv` whereas we only had the link to the webpage. I'll fix this soon in a small PR

**Comment by jannisborn** [comment]
Closed via [529c06a](https://github.com/jannisborn/covid19_ultrasound/commit/529c06a651ee42fb4d47445f72eede0ed3337245)
