### ISSUE TITLE
Butterfly data

### ISSUE THREAD

**Issue by shaibagon** [jannisborn/covid19_ultrasound#81]
1. I'm having trouble downloading the butterfly data:  
I press the "download" icon and my request "is processed", but eventually I get an error 
> File requested not found

Is there an alternative way of getting this data?

2.  Once I obtain the data, the README instruct to run `sh parse_butterfly.sh`. For some reason I don't find this script in the repository. Am I missing something here?

**Comment by jannisborn** [comment]
I guess you're talking about this link: https://www.butterflynetwork.com/covid19/covid-19-ultrasound-gallery

I can still see the Download button but I receive the same error. Unfortunately, this data is external and we dont have the rights to redistribute it, that's why we provide the script.

I would advice asking the Butterfly bot. Maybe they only temporarily disabled it. Maybe it's also a mistake, since the website is still up. You can keep us posted here.

**Comment by jannisborn** [comment]
Regarding 2): You're right! Sorry, we were recently doing a larger refactor and this file got lost in the cracks since `.sh` files are in the `.gitignore`. Restored it now.

Closing this for the moment, but feel free to reopen regarding 1)

**Comment by shaibagon** [comment]
@jannisborn Thanks for the prompt response.

As for the butterfly gallery - I found it in a slightly different url:

go to:
https://www.butterflynetwork.com/covid-19

scroll to "download gallery" - this time it works.

direct link: https://butterflynetwork.getbynder.com/transfer/13018dc5548307d38db1dff511ba422708fc2f7e8cfab51af09205e25046b23e


Thanks!

**Comment by jannisborn** [comment]
Great stuff, thx for the heads-up. I will update the README asap.
