### ISSUE TITLE
split data how its work !!!

### ISSUE THREAD

**Issue by TIKO1993** [jannisborn/covid19_ultrasound#87]
hi i would like to thank you guys for this wonderful work , just i have a question about how can i split the dataset , after the using the explaination in read e i got a dataset of 3 classes (covid, pnemounia, regular), i start working with the dataset , and i split the dataset randomly in 80% for training and 20% for test im just asking if this is a good why to split the dataset , it seems that the test will content also the images token from the videos for the training

**Comment by jannisborn** [comment]
HI @TIKO1993, thanks for your interest in our work. I think the README is pretty clear about this (see https://github.com/jannisborn/covid19_ultrasound/tree/master/pocovidnet#cross-validation-splitting).

If you randomly split the images into 80/20 train/test your split will be meaningless. Your performance will be almost perfect but it will mean nothing. You have to split on the video level, not on the image level, that's why we provide the code to split the data correctly for you.

**Comment by TIKO1993** [comment]
sir could you please explain more, so i split the to 5 folders i will train the model on 4 folders and i keep 1 folder for test ???

**Comment by jannisborn** [comment]
If you follow the readme, things are being set up for you correctly.

**Comment by TIKO1993** [comment]
it's ok thank you
