### ISSUE TITLE
Labelisation errors

### ISSUE THREAD

**Issue by Alexc75** [jannisborn/covid19_ultrasound#89]
Hi, 
We are leading a study thanks to your dataset and we reviewed the sequences with radiologists and noticed labeling errors amongst the data. 
We also launched a new labelisation on a symptom level (A-lines, B-Lines, Pleural irregularities, etc) 
We'll post more information soon if interested.

**Comment by jannisborn** [comment]
Hi @Alexc75,
Thanks for the great effort and getting in touch, that sounds very exciting! It's these sort of projects that we fancied when creating this data resource as a community initiative.

We'd certainly be interested to have a look at potential labelling errors. We performed several rounds of verifying sources and checking the data, but since the sources are so heterogeneous, errors can always happen.

Regarding symptoms: Some members from our team also labelled on a symptom level. All meta-data for every video/image in this database, can be found here: https://github.com/jannisborn/covid19_ultrasound/blob/master/data/dataset_metadata.csv 
There are columns for the lung US symptoms (Effusion | Consolidations | B-lines | A-lines | Pleural line irregularities | Air bronchogram) and also for patient symptoms (fever etc., when available). Were you aware of that? Maybe we should have made it more clear in the READMEs. In any way, having an independent validation on that end would certainly also help :)

Please keep us posted here!

**Comment by jannisborn** [comment]
Please reopen if applicable @Alexc75
