### ISSUE TITLE
redis.conf file is missing in .ddev/redis

### ISSUE THREAD

**Issue by jemmimarg** [jannisborn/covid19_ultrasound#93]
There are actually three major issues I faced while trying to run the code,
1.  Open CV dependencies are not installed in the docker file. This issue was solved by adding `RUN apt-get update && apt-get install -y python3-opencv`
2. The training parameters/ weights are not available on github and hence pocovidnet failed to run. To solve this issue I downloaded the weight from the google drive link in the read me file. I also had to change the path from ../training_model_cams/fold_0/best_weights/variales/variables to training_model_cams/fold_0/variables/variables.
3. The redis.conf file is missing from ./ddev/redis I tried putting the example config file in there and running it but that fails as well.
Any help to sort this out ASAP would be appreciated.

I have not been able to move past the `ddev start` step.

**Comment by NinaWie** [comment]
Hi @jemmimarg , thanks for your interest in our project and for the questions.

Regarding point 1 and 3: The docker file and the `pocovidscreen` folder are only related to our website and are not needed to train and run a model. All instructions how to install the repository and to run the code are in the two READMEs and they don't involve the docker file. 

For point 2: The trained models are only on Google Drive on purpose, because git is not suitable for tracking binaries. Thank you for noticing the issue in the path; we will correct this. 
Please let me know if you have further questions.
